// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7h3HFhxI2N1qwlmJcxnysVxtCCRscaOA',
    appId: '1:18304713164:web:0c6f24daac3e531a9cdd69',
    messagingSenderId: '18304713164',
    projectId: 'plantmitra-ae339',
    authDomain: 'plantmitra-ae339.firebaseapp.com',
    storageBucket: 'plantmitra-ae339.firebasestorage.app',
    measurementId: 'G-L68PC04XHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Rt6m0wz04Hqh8P81iyRm9WqxpT-ZMI4',
    appId: '1:18304713164:android:ebcfd23f5ec077309cdd69',
    messagingSenderId: '18304713164',
    projectId: 'plantmitra-ae339',
    storageBucket: 'plantmitra-ae339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiatJKU8x3z-Nguh2RacbHXkxrBj9ZRZ0',
    appId: '1:18304713164:ios:8776ed9852c550419cdd69',
    messagingSenderId: '18304713164',
    projectId: 'plantmitra-ae339',
    storageBucket: 'plantmitra-ae339.firebasestorage.app',
    iosBundleId: 'com.example.plantmitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiatJKU8x3z-Nguh2RacbHXkxrBj9ZRZ0',
    appId: '1:18304713164:ios:8776ed9852c550419cdd69',
    messagingSenderId: '18304713164',
    projectId: 'plantmitra-ae339',
    storageBucket: 'plantmitra-ae339.firebasestorage.app',
    iosBundleId: 'com.example.plantmitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7h3HFhxI2N1qwlmJcxnysVxtCCRscaOA',
    appId: '1:18304713164:web:cd87bb34d4dc03199cdd69',
    messagingSenderId: '18304713164',
    projectId: 'plantmitra-ae339',
    authDomain: 'plantmitra-ae339.firebaseapp.com',
    storageBucket: 'plantmitra-ae339.firebasestorage.app',
    measurementId: 'G-PBCPE279XC',
  );
}
